version: '3.8'

services:
  db:
    image: postgres
    restart: always
    ports:
      # https://stackoverflow.com/questions/37775702/changing-a-postgres-containers-server-port-in-docker-compose
      # I want to host this local database on another port (5433) than Outzoner
      # I changed it back to 5432 because it looks more beautiful :))
      - 5432:5432
    environment:
      # https://hub.docker.com/_/postgres: Default values for these values in Docker
      POSTGRES_USER: songqueue
      POSTGRES_PASSWORD: songqueue
    volumes:
      - db:/var/lib/postgresql/data

  cache:
    image: redis:7.0-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass songqueue
    volumes:
      - cache:/data

  localstack:
    image: localstack/localstack
    ports:
      - '4566:4566' # LocalStack Gateway
      - '4510-4559:4510-4559' # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - SERVICES=s3
    volumes:
      - '${LOCALSTACK_VOLUME_DIR:-./.s3local}:/var/lib/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'

  aws-cli:
    image: amazon/aws-cli
    depends_on:
      - localstack
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-2
    entrypoint: /bin/sh -c
    command: >
      "
        aws --endpoint-url=http://localstack:4566 s3api create-bucket --bucket songqueue --region us-east-1
        echo '{\"CORSRules\": [{\"AllowedHeaders\": [\"*\"],\"AllowedMethods\": [\"GET\", \"POST\", \"PUT\",\"HEAD\", \"DELETE\"],\"AllowedOrigins\": [\"${S3_CORS_ALLOWED_ORIGINS}\", \"https://app.localstack.cloud\", \"http://app.localstack.cloud\"],\"ExposeHeaders\": [\"ETag\"]}]}' >> cors.json
        aws --endpoint-url=http://localstack:4566 s3api put-bucket-cors --bucket songqueue --cors-configuration file://cors.json
        tail -F anything
      "

volumes:
  db:
  cache:
